# Generated by Django 5.2.6 on 2025-10-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del Rol')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_u', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('nombre_p', models.CharField(blank=True, max_length=75, null=True, verbose_name='Nombre Personal')),
                ('telefono', models.CharField(blank=True, max_length=75, null=True, verbose_name='Teléfono')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.role', verbose_name='Rol')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'db_table': 'usuariosroles',
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
    ]
