# Generated by Django 5.2.6 on 2025-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha del Reporte')),
                ('total_ventas_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Ventas del Día')),
                ('numero_pedidos_dia', models.IntegerField(verbose_name='Número de Pedidos del Día')),
                ('productos_mas_vendidos', models.TextField(blank=True, null=True, verbose_name='JSON de Productos más Vendidos')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Reporte de Ventas',
                'verbose_name_plural': 'Reportes de Ventas',
                'db_table': 'reporte',
            },
        ),
    ]
