# Generated by Django 5.2.6 on 2025-10-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero', models.CharField(max_length=20, verbose_name='Número Exterior/Interior De Casa')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio/Localidad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('referencia', models.TextField(blank=True, null=True, verbose_name='Referencia Adicional')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Dirección de Usuario',
                'verbose_name_plural': 'Direcciones de Usuarios',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del Pedido')),
                ('estado_pedido', models.CharField(default='PENDIENTE', max_length=50, verbose_name='Estado del Pedido')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('id_direccion', models.ForeignKey(blank=True, db_column='id_direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.direccion', verbose_name='Dirección de Entrega')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario que realiza el pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ArticuloPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Comprada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='productos.producto', verbose_name='Producto Comprado')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Artículo de Pedido',
                'verbose_name_plural': 'Artículos de Pedidos',
                'db_table': 'articulopedido',
                'unique_together': {('id_pedido', 'id_producto')},
            },
        ),
    ]
